Add ci workflow + LICENSE
chain4travel/camino-messenger-bot pull request #20
Opened 2024-04-23 11:30 UTC by knikos

2024-05-16 13:46 UTC, mo-c4t submitted a review, later dismissed
LGTM

2024-05-16 13:49 UTC, evlekht requested changes

2024-05-16 13:49 UTC, evlekht commented on config/config.go
> -	viper.ReadInConfig() // ignore config-file-reading-errors as we have env vars as fallback configuration
I think app should log warn if it failed to read config file. And in order to avoid file-not-found errors, we can also check for file first, maybe

2024-05-17 08:49 UTC, evlekht approved these changes

2024-05-17 08:56 UTC, merged